### ISSUE TITLE
[yahoo] error case that audio is not found has not been handled

### ISSUE THREAD

**Issue by zlargon** [zlargon/voc#6]
```
$ voc philanthropicminde -y

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.extname (path.js:1433:5)
    at _callee$ (/Users/zlargon/GitHub/voc/bin/getAudio.js:50:34)
    at tryCatch (/Users/zlargon/GitHub/voc/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/zlargon/GitHub/voc/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/zlargon/GitHub/voc/node_modules/regenerator-runtime/runtime.js:95:21)
    at onFulfilled (/Users/zlargon/GitHub/voc/node_modules/co/index.js:65:19)
    at run (/Users/zlargon/GitHub/voc/node_modules/core-js/modules/es6.promise.js:89:22)
    at /Users/zlargon/GitHub/voc/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/Users/zlargon/GitHub/voc/node_modules/core-js/modules/_microtask.js:18:9)
```

**Comment by zlargon** [comment]
```
$ voc philanthropicminde -y
'philanthropicminde' has no audio from yahoo
```
