### ISSUE TITLE
throwing wrong exception when word is not found

### ISSUE THREAD

**Issue by zlargon** [zlargon/voc#8]
```
$ voc aaaaaa
Error: request to http://www.merriam-webster.com/dictionary/aaaaaa failed, status code = 404 (Not Found)
    at Object._callee$ (/Users/zlargon/GitHub/voc/bin/dic/webster.js:28:17)
    at tryCatch (/Users/zlargon/GitHub/voc/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/zlargon/GitHub/voc/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/zlargon/GitHub/voc/node_modules/regenerator-runtime/runtime.js:95:21)
    at onFulfilled (/Users/zlargon/GitHub/voc/node_modules/co/index.js:65:19)
    at run (/Users/zlargon/GitHub/voc/node_modules/core-js/modules/es6.promise.js:89:22)
    at /Users/zlargon/GitHub/voc/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/Users/zlargon/GitHub/voc/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by zlargon** [comment]
```
$ voc aaaaaa
'aaaaaa' is not found
```
